"""Add indexes to foreign keys

Revision ID: 05875d98fcec
Revises: 24146718ab12
Create Date: 2026-09-10 18:08:02.391873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05875d98fcec'
down_revision: Union[str, Sequence[str], None] = '24146718ab12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_access_grant_id'), 'audit_logs', ['access_grant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_access_request_id'), 'audit_logs', ['access_request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_hospital_id'), 'audit_logs', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_patient_id'), 'audit_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_document_access_grants_access_request_id'), 'document_access_grants', ['access_request_id'], unique=False)
    op.create_index(op.f('ix_document_access_grants_doctor_id'), 'document_access_grants', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_document_access_grants_hospital_id'), 'document_access_grants', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_document_access_grants_patient_id'), 'document_access_grants', ['patient_id'], unique=False)
    op.create_index(op.f('ix_document_access_requests_patient_id'), 'document_access_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_document_access_requests_requesting_doctor_id'), 'document_access_requests', ['requesting_doctor_id'], unique=False)
    op.create_index(op.f('ix_document_access_requests_requesting_hospital_id'), 'document_access_requests', ['requesting_hospital_id'], unique=False)
    op.create_index(op.f('ix_medical_documents_hospital_id'), 'medical_documents', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_medical_documents_patient_id'), 'medical_documents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_documents_uploaded_by_doctor_id'), 'medical_documents', ['uploaded_by_doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_documents_visit_id'), 'medical_documents', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_documents_visit_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_uploaded_by_doctor_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_patient_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_hospital_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_document_access_requests_requesting_hospital_id'), table_name='document_access_requests')
    op.drop_index(op.f('ix_document_access_requests_requesting_doctor_id'), table_name='document_access_requests')
    op.drop_index(op.f('ix_document_access_requests_patient_id'), table_name='document_access_requests')
    op.drop_index(op.f('ix_document_access_grants_patient_id'), table_name='document_access_grants')
    op.drop_index(op.f('ix_document_access_grants_hospital_id'), table_name='document_access_grants')
    op.drop_index(op.f('ix_document_access_grants_doctor_id'), table_name='document_access_grants')
    op.drop_index(op.f('ix_document_access_grants_access_request_id'), table_name='document_access_grants')
    op.drop_index(op.f('ix_audit_logs_patient_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_hospital_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_access_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_access_grant_id'), table_name='audit_logs')
    # ### end Alembic commands ###
