"""add_scan_status

Revision ID: af6896e54190
Revises: ded82bbdc484
Create Date: 2026-09-11 08:20:21.476286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6896e54190'
down_revision: Union[str, Sequence[str], None] = 'ded82bbdc484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_documents', sa.Column('scan_status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_documents', 'scan_status')
    # ### end Alembic commands ###
