"""Hospital authorization

Revision ID: f97246538419
Revises: f79c0d63474b
Create Date: 2026-09-09 08:11:07.539120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97246538419'
down_revision: Union[str, Sequence[str], None] = 'f79c0d63474b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_staff') as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
    with op.batch_alter_table('triage_requests') as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_triage_requests_hospital_id', 'hospitals', ['hospital_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_requests') as batch_op:
        batch_op.drop_constraint('fk_triage_requests_hospital_id', type_='foreignkey')
        batch_op.drop_column('hospital_id')
    with op.batch_alter_table('hospital_staff') as batch_op:
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###
