from pathlib import Path


def rep(path, old, new, n=1):
    p = Path(path); text = p.read_text(); found = text.count(old)
    if found != n: raise SystemExit(f"{path}: expected {n}, found {found}: {old[:70]!r}")
    p.write_text(text.replace(old, new))

p = "patient-app/src/components/Layout.tsx"
rep(p, "import { Activity, FileText, Lock, History, User, Bell, LogOut, Menu, Calendar } from 'lucide-react';", "import { Activity, FileText, Lock, History, User, Bell, LogOut, Calendar } from 'lucide-react';\nimport { ConnectionStatus } from '@shared/ui/ConnectionStatus';")
rep(p, '''          <div className="flex items-center gap-2 mb-4 px-2">\n            <div className={`w-2.5 h-2.5 rounded-full ${wsStatus === 'connected' ? 'bg-emerald-500' : (wsStatus === 'connecting' ? 'bg-amber-500' : 'bg-red-500')}`}></div>\n            <span className="text-xs text-slate-400 font-medium">\n              {wsStatus === 'connected' ? 'System Live' : (wsStatus === 'connecting' ? 'Connecting...' : 'Offline')}\n            </span>\n          </div>''', '''          <ConnectionStatus status={wsStatus} className="mb-4 px-2 text-slate-300" />''')
rep(p, '''            <button className="md:hidden p-2 text-slate-500 hover:bg-slate-100 rounded-md transition-colors">\n              <Menu className="h-5 w-5" />\n            </button>\n''', '')
rep(p, '''            <button \n              onClick={() => navigate('/notifications')} \n              className="relative p-2 text-slate-500 hover:bg-slate-100 rounded-full transition-colors"\n            >''', '''            <button\n              type="button"\n              aria-label={unreadCount > 0 ? `Notifications, ${unreadCount} unread` : 'Notifications'}\n              onClick={() => navigate('/notifications')}\n              className="relative min-h-11 min-w-11 p-2 text-slate-600 hover:bg-slate-100 rounded-full transition-colors focus-visible:ring-2 focus-visible:ring-blue-600"\n            >''')
rep(p, '''            <div className="h-8 w-8 rounded-full bg-primary/10 text-primary flex items-center justify-center font-bold text-sm border border-primary/20">\n              P\n            </div>''', '''            <div className="h-9 w-9 rounded-full bg-primary/10 text-primary flex items-center justify-center font-bold text-sm border border-primary/20" aria-label="Patient account">\n              {(patientProfile?.full_name || patientProfile?.email || 'Patient').trim().charAt(0).toUpperCase()}\n            </div>''')
rep(p, '<main className="flex-1 overflow-y-auto p-4 md:p-6 lg:p-8">', '<main id="patient-main" className="flex-1 overflow-y-auto p-4 pb-28 md:p-6 md:pb-6 lg:p-8" tabIndex={-1}>')
rep(p, '''        </main>\n      </div>\n    </div>''', '''        </main>\n        <nav className="safe-bottom fixed inset-x-0 bottom-0 z-40 border-t border-slate-200 bg-white/95 shadow-[0_-8px_24px_rgba(15,23,42,0.08)] backdrop-blur md:hidden" aria-label="Patient mobile navigation">\n          <div className="flex overflow-x-auto px-1">\n            {[\n              { path: '/dashboard', label: 'Overview', icon: Activity },\n              { path: '/appointments', label: 'Visits', icon: Calendar },\n              { path: '/documents', label: 'Records', icon: FileText },\n              { path: '/access-requests', label: 'Consent', icon: Lock },\n              { path: '/profile', label: 'Profile', icon: User },\n            ].map((item) => {\n              const Icon = item.icon; const active = location.pathname === item.path;\n              return <Link key={item.path} to={item.path} aria-current={active ? 'page' : undefined} className={`flex min-h-16 min-w-[5rem] flex-1 flex-col items-center justify-center gap-1 px-2 text-[11px] font-semibold ${active ? 'text-blue-800' : 'text-slate-600'}`}><Icon className="h-5 w-5" aria-hidden="true" />{item.label}</Link>;\n            })}\n          </div>\n        </nav>\n      </div>\n    </div>''')
rep(p, "toast.success('Symptoms submitted successfully!');", "toast.success('Symptoms submitted for clinician review.');")
rep(p, 'await fetchRequests(); // refresh immediately to show AI result', 'await fetchRequests(); // Refresh recorded triage-support status.')

p = "doctor-portal/src/components/Layout.tsx"
rep(p, "import { Activity, Users, User, FileText, Lock, Bell, LogOut, Menu, Shield, Calendar } from 'lucide-react';", "import { Activity, Users, User, FileText, Lock, Bell, LogOut, Shield, Calendar } from 'lucide-react';\nimport { ConnectionStatus } from '@shared/ui/ConnectionStatus';")
rep(p, 'export interface TriageRequest {\n  id: number;\n  symptoms: string;', 'export interface TriageRequest {\n  id: number;\n  patient_id: number;\n  symptoms: string;')
rep(p, '''          <div className="flex items-center gap-2 mb-4 px-2">\n            <div className="relative flex h-2.5 w-2.5">\n              {wsStatus === 'connected' && (\n                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />\n              )}\n              <span className={`relative inline-flex rounded-full h-2.5 w-2.5 ${wsStatus === 'connected' ? 'bg-emerald-500' : (wsStatus === 'connecting' ? 'bg-amber-500' : 'bg-rose-500')}`} />\n            </div>\n            <span className="text-xs text-slate-400 font-medium tracking-wide">\n              {wsStatus === 'connected' ? 'System Live & Synced' : (wsStatus === 'connecting' ? 'Connecting...' : 'Offline - Reconnecting')}\n            </span>\n          </div>''', '''          <ConnectionStatus status={wsStatus} className="mb-4 px-2 text-slate-300" />''')
rep(p, '''            <button className="md:hidden p-2 text-slate-500 hover:bg-slate-100 rounded-md transition-colors">\n              <Menu className="h-5 w-5" />\n            </button>\n''', '')
rep(p, '<p className="text-xs text-slate-500 mt-1 font-medium">General Hospital</p>', '<p className="text-xs text-slate-500 mt-1 font-medium">Authenticated clinical workspace</p>')
rep(p, '<main className="flex-1 overflow-y-auto p-4 md:p-6 lg:p-8 bg-slate-50 relative">', '<main id="doctor-main" className="flex-1 overflow-y-auto p-4 pb-28 md:p-6 md:pb-6 lg:p-8 bg-slate-50 relative" tabIndex={-1}>')
rep(p, '''        </main>\n      </div>\n    </div>''', '''        </main>\n        <nav className="safe-bottom fixed inset-x-0 bottom-0 z-40 border-t border-slate-200 bg-white/95 shadow-[0_-8px_24px_rgba(15,23,42,0.08)] backdrop-blur md:hidden" aria-label="Clinician mobile navigation">\n          <div className="flex overflow-x-auto px-1">\n            {navItems.map((item) => {\n              const Icon = item.icon; const active = location.pathname === item.path;\n              return <Link key={item.path} to={item.path} aria-current={active ? 'page' : undefined} className={`relative flex min-h-16 min-w-[5.25rem] flex-1 flex-col items-center justify-center gap-1 px-2 text-[11px] font-semibold ${active ? 'text-blue-800' : 'text-slate-600'}`}><Icon className="h-5 w-5" aria-hidden="true" />{item.label}{!!item.badge && <span className="absolute right-2 top-1 rounded-full bg-rose-700 px-1.5 text-[10px] text-white" aria-label={`${item.badge} unread`}>{item.badge}</span>}</Link>;\n            })}\n          </div>\n        </nav>\n      </div>\n    </div>''')

p = "patient-app/src/pages/AccessRequests.tsx"
rep(p, '  console.log("AccessRequests Render - confirmApproveId:", confirmApproveId, "isOpen:", !!confirmApproveId);\n\n', '')
rep(p, "import { toast } from 'react-hot-toast';\n", '')
rep(p, '''                    <p className="text-sm font-medium text-slate-700 mb-3 flex items-center gap-2">\n                      <Clock className="h-4 w-4 text-slate-500" />\n                      Allow access for:\n                    </p>\n                    <div className="flex flex-col sm:flex-row gap-3">\n                      <Select \n                        value={duration} ''', '''                    <label htmlFor={`grant-duration-${req.id}`} className="text-sm font-medium text-slate-700 mb-3 flex items-center gap-2">\n                      <Clock className="h-4 w-4 text-slate-500" aria-hidden="true" />\n                      Allow access for\n                    </label>\n                    <div className="flex flex-col sm:flex-row gap-3">\n                      <Select\n                        id={`grant-duration-${req.id}`}\n                        value={duration} ''')
rep(p, '''                          onClick={() => {\n                            toast('Please confirm approval in the popup window.', { icon: 'ℹ️' });\n                            setConfirmApproveId(req.id);\n                          }}''', '''                          onClick={() => setConfirmApproveId(req.id)}''')
rep(p, '''                          onClick={() => {\n                            toast('Please confirm rejection in the popup window.', { icon: 'ℹ️' });\n                            setConfirmRejectId(req.id);\n                          }}''', '''                          onClick={() => setConfirmRejectId(req.id)}''')

p = "patient-app/src/pages/Profile.tsx"
rep(p, 'AI Assessment', 'Automated triage support')

Path('scripts/apply_ui_layout_patch.py').unlink()
Path('.github/workflows/ui-readiness-layout-patch.yml').unlink()
print('UI layout patch applied')
